name       : steam
version    : 1.0.0.62
release    : 67
source     :
    - https://repo.steampowered.com/steam/pool/steam/s/steam/steam_1.0.0.62.tar.gz : 83cbff7379b3ef8115e651fb1b627be5f9b38d0e8b405e8bcd91871df5f588df
homepage   : https://store.steampowered.com
license    : Distributable
component  : games
summary    : Launcher for the Steam software distribution service
description: |
    Launcher for the Steam software distribution service
rundeps    :
    - acl-32bit
    - alsa-plugins-32bit
    - attr-32bit
    - bzip2-32bit
    - cups-32bit
    - curl-32bit
    - curl-gnutls-32bit
    - dconf-32bit
    - diffutils
    - freeglut-32bit
    - gconf-32bit
    - glew110-32bit
    - glew-32bit
    - glibc-32bit
    - gmp-32bit
    - gnome-themes-extra-32bit
    - gperftools-32bit
    - gst-plugins-base-32bit
    - gstreamer-0.10-32bit
    - gtk2-engine-murrine-32bit
    - harfbuzz-32bit
    - intel-tbb-32bit
    - json-c-32bit
    - kerberos-32bit
    - libappindicator-32bit
    - libatk-32bit
    - libav
    - libcap2-32bit
    - libdatrie
    - libgcc-32bit
    - libgcrypt11-32bit
    - libgcrypt-32bit
    - libglu-32bit
    - libgomp-32bit
    - libgudev-32bit
    - libhogweed-32bit
    - libidn-32bit
    - libjpeg-turbo6-32bit
    - libmikmod2-32bit
    - libnm-legacy-32bit
    - libnspr-32bit
    - libnss-32bit
    - libpcre-32bit
    - libpcre3-32bit
    - libpng12-32bit
    - libpng15-32bit
    - libpng-32bit
    - libressl-shim-32bit
    - librsvg-32bit
    - libselinux
    - libthai
    - libtheora-32bit
    - libtxc_dxtn-32bit
    - libunistring-32bit
    - libusb-32bit
    - libva-32bit
    - libva1-32bit
    - libvdpau-32bit
    - libvpx1-32bit
    - libx11-32bit
    - libxcomposite-32bit
    - libxcursor-32bit
    - libxdmcp-32bit
    - libxext-32bit
    - libxft-32bit
    - libxi-32bit
    - libxmu-32bit
    - libxrandr-32bit
    - libxscrnsaver-32bit
    - libxshmfence-32bit
    - libxtst-32bit
    - libxxf86dga-32bit
    - libxxf86vm-32bit
    - linux-steam-integration
    - mesalib-32bit
    - mpg123-32bit
    - nas-32bit
    - ncurses-32bit
    - network-manager-32bit
    - openal-soft-32bit
    - openldap-32bit
    - pulseaudio-32bit
    - rtmpdump-32bit
    - sdl1-32bit
    - sdl1-image-32bit
    - sdl1-mixer-32bit
    - sdl1-net-32bit
    - sdl2-32bit
    - sdl2-gfx-32bit
    - sdl2-image-32bit
    - sdl2-mixer-32bit
    - sdl2-net-32bit
    - sdl2-ttf-32bit
    - sdl-gfx-32bit
    - sdl-ttf-32bit
    - systemd-32bit
    - tcp_wrappers-32bit
    - vulkan-32bit
    - xz-32bit
    - zenity
    - zlib-32bit
install    : |
    %patch -p1 < $pkgfiles/fix-udev-rules.patch
    %make_install install-bin install-docs install-icons install-bootstrap install-desktop
    install -Ddm00755 $installdir/%libdir%/udev/rules.d
    install -m00644 subprojects/steam-devices/* $installdir/%libdir%/udev/rules.d/.

    # Remove license
    rm -v $installdir/%libdir%/udev/rules.d/LICENSE

    # Integrate with LSI.
    mv $installdir/usr/bin/steam $installdir/usr/lib/steam/.
