name       : steam
version    : 1.0.0.54
release    : 36
source     :
    - http://repo.steampowered.com/steam/pool/steam/s/steam/steam_1.0.0.54.tar.gz : 42531bf2615afed54c333ae9afeebe8cb68a31304ddfcf90e61b3532a5597386
license    : Distributable
component  : games
summary    : Launcher for the Steam software distribution service
description: |
    Launcher for the Steam software distribution service
rundeps    :
    - acl-32bit
    - alsa-plugins-32bit
    - attr-32bit
    - bzip2-32bit
    - cups-32bit
    - curl-32bit
    - curl-gnutls-32bit
    - dconf-32bit
    - freeglut-32bit
    - gconf-32bit
    - glew110-32bit
    - glibc-32bit
    - gnome-themes-standard-32bit
    - gtk2-engine-murrine-32bit
    - harfbuzz-32bit
    - intel-tbb-32bit
    - kerberos-32bit
    - libappindicator-32bit
    - libatk-32bit
    - libcap2-32bit
    - libgcc-32bit
    - libgcrypt11-32bit
    - libgcrypt-32bit
    - libglu-32bit
    - libgomp-32bit
    - libidn-32bit
    - libjpeg-turbo6-32bit
    - libnspr-32bit
    - libnss-32bit
    - libpcre-32bit
    - libpcre3-32bit
    - libpng12-32bit
    - libpng-32bit
    - libtheora-32bit
    - libtxc_dxtn-32bit
    - libunistring-32bit
    - libusb-32bit
    - libx11-32bit
    - libxcomposite-32bit
    - libxcursor-32bit
    - libxdmcp-32bit
    - libxext-32bit
    - libxi-32bit
    - libxft-32bit
    - libxmu-32bit
    - libxrandr-32bit
    - libxscrnsaver-32bit
    - libxshmfence-32bit
    - libxtst-32bit
    - libxxf86dga-32bit
    - libxxf86vm-32bit
    - linux-steam-integration
    - mesalib-32bit
    - network-manager-32bit
    - openal-soft-32bit
    - openldap-32bit
    - pulseaudio-32bit
    - rtmpdump-32bit
    - sdl1-32bit
    - sdl1-image-32bit
    - sdl1-mixer-32bit
    - sdl1-net-32bit
    - sdl2-32bit
    - sdl2-gfx-32bit
    - sdl2-image-32bit
    - sdl2-mixer-32bit
    - sdl2-net-32bit
    - sdl-gfx-32bit
    - sdl-ttf-32bit
    - systemd-32bit
    - tcp_wrappers-32bit
    - xz-32bit
install    : |
    %patch -p1 < $pkgfiles/fix-udev-rules.patch
    %make_install install-bin install-docs install-icons install-bootstrap install-desktop
    install -D -d -m 00755 $installdir/%libdir%/udev/rules.d
    install -m 00644 lib/udev/rules.d/* $installdir/%libdir%/udev/rules.d/.

    # Integrate with LSI.
    mv $installdir/usr/bin/steam $installdir/usr/lib/steam/.
