name       : steam
version    : 1.0.0.52
release    : 13
source     :
    - http://repo.steampowered.com/steam/pool/steam/s/steam/steam_1.0.0.52.tar.gz : dd3b1a9f597bf0e088094d6fd1e495068434b604346139f277ea26c41e009304
license    : Distributable
component  : nonfree
summary    : Launcher for the Steam software distribution service
description: |
    Launcher for the Steam software distribution service
rundeps    :
    - acl-32bit
    - attr-32bit
    - cups-32bit
    - curl-gnutls-32bit
    - gconf-32bit
    - glibc-32bit
    - gnome-themes-standard-32bit
    - gtk2-engine-murrine-32bit
    - harfbuzz-32bit
    - libatk-32bit
    - libcap2-32bit
    - libgcc-32bit
    - libgcrypt-32bit
    - libgcrypt11-32bit
    - libnspr-32bit
    - libnss-32bit
    - libpng-32bit
    - libtxc_dxtn-32bit
    - libusb-32bit
    - libx11-32bit
    - libxcomposite-32bit
    - libxcursor-32bit
    - libxext-32bit
    - libxi-32bit
    - libxrandr-32bit
    - libxscrnsaver-32bit
    - libxshmfence-32bit
    - libxtst-32bit
    - libxxf86dga-32bit
    - libxxf86vm-32bit
    - mesalib-32bit
    - network-manager-32bit
    - openal-soft-32bit
    - pulseaudio-32bit
    - sdl2-32bit
    - systemd-32bit
    - xz-32bit
install    : |
    %make_install install-bin install-docs install-icons install-bootstrap install-desktop
    install -D -d -m 00755 $installdir/%libdir%/udev/rules.d
    install -m 00644 lib/udev/rules.d/* $installdir/%libdir%/udev/rules.d/.
