name       : steam
version    : 1.0.0.51
release    : 2
source     :
    - http://repo.steampowered.com/steam/pool/steam/s/steam/steam_1.0.0.51.tar.gz : bf766db05fcc3a8079e7e514accfbd2503813a3c70ff8336aa93e554ed7719be
license    : Distributable
summary    : Launcher for the Steam software distribution service
description: |
    Launcher for the Steam software distribution service
rundeps    :
    - glibc-32bit
    - libgcc-32bit
    - libx11-32bit
    - libxext-32bit
    - libtxc_dxtn-32bit
    - mesalib-32bit
install    : |
    %make_install install-bin install-docs install-icons install-bootstrap install-desktop
