name       : steam
version    : 1.0.0.52
release    : 9
source     :
    - http://repo.steampowered.com/steam/pool/steam/s/steam/steam_1.0.0.52.tar.gz : dd3b1a9f597bf0e088094d6fd1e495068434b604346139f277ea26c41e009304
license    : Distributable
summary    : Launcher for the Steam software distribution service
description: |
    Launcher for the Steam software distribution service
rundeps    :
    - glibc-32bit
    - libgcc-32bit
    - libx11-32bit
    - libxext-32bit
    - libtxc_dxtn-32bit
    - mesalib-32bit
    - libxshmfence-32bit
    - libxtst-32bit
    - gtk2-engine-murrine-32bit
    - gnome-themes-standard-32bit
    - libxrandr-32bit
    - libatk-32bit
    - harfbuzz-32bit
    - systemd-32bit
    - libcap2-32bit
    - attr-32bit
    - acl-32bit
install    : |
    %make_install install-bin install-docs install-icons install-bootstrap install-desktop
    install -D -d -m 00755 $installdir/%libdir%/udev/rules.d
    install -m 00644 lib/udev/rules.d/* $installdir/%libdir%/udev/rules.d/.
