name       : steam
version    : 1.0.0.70
release    : 76
source     :
    - https://repo.steampowered.com/steam/pool/steam/s/steam/steam_1.0.0.70.tar.gz : 9ff88a5778c7b00efb18f324d4cd0c282d5f438dad1201bc3e9822e3ff6a2dff
homepage   : https://store.steampowered.com
license    : Distributable
component  : games
summary    : Launcher for the Steam software distribution service
description: |
    Launcher for the Steam software distribution service
rundeps    :
    - acl-32bit
    - alsa-plugins-32bit
    - attr-32bit
    - bzip2-32bit
    - curl-gnutls-32bit
    - dconf-32bit
    - diffutils
    - freeglut-32bit
    - gconf-32bit
    - glew110-32bit
    - glew-32bit
    - gnome-themes-extra-32bit
    - gperftools-32bit
    - gst-plugins-base-32bit
    - gtk2-engine-murrine-32bit
    - hidapi-32bit
    - intel-tbb-32bit
    - json-c-32bit
    - libappindicator-32bit
    - libav
    - libcap2-32bit
    - libgcrypt11-32bit
    - libgcrypt-32bit
    - libglu-32bit
    - libgomp-32bit
    - libgudev-32bit
    - libidn-32bit
    - libjpeg-turbo6-32bit
    - libmikmod2-32bit
    - libnettle6-32bit
    - libnm-legacy-32bit
    - libpcre3-32bit
    - libpng12-32bit
    - libpng15-32bit
    - libressl-shim-32bit
    - librsvg-32bit
    - libselinux
    - libthai
    - libtxc_dxtn-32bit
    - libva-32bit
    - libva1-32bit
    - libvdpau-32bit
    - libvpx1-32bit
    - libxmu-32bit
    - libxscrnsaver-32bit
    - libxxf86dga-32bit
    - linux-steam-integration
    - mesalib-32bit
    - mpg123-32bit
    - nas-32bit
    - ncurses-32bit
    - network-manager-32bit
    - openal-soft-32bit
    - openldap-32bit
    - openssl-32bit
    - pciutils-32bit
    - pipewire-32bit
    - sdl1-image-32bit
    - sdl1-mixer-32bit
    - sdl1-net-32bit
    - sdl2-gfx-32bit
    - sdl2-image-32bit
    - sdl2-mixer-32bit
    - sdl2-net-32bit
    - sdl2-ttf-32bit
    - sdl-gfx-32bit
    - sdl-ttf-32bit
    - tcp_wrappers-32bit
    - vulkan-32bit
    - zenity
install    : |
    %patch -p1 < $pkgfiles/fix-udev-rules.patch
    %make_install install-bin install-docs install-icons install-bootstrap install-desktop
    install -Ddm00755 $installdir/%libdir%/udev/rules.d
    install -m00644 subprojects/steam-devices/* $installdir/%libdir%/udev/rules.d/.

    # Remove license
    rm -v $installdir/%libdir%/udev/rules.d/LICENSE

    # Integrate with LSI.
    mv $installdir/usr/bin/steam $installdir/usr/lib/steam/.
